name: "WCAG issues"
description: "Include WCAG related GitHub issues in your WCAG-EM report."
author: "Frameless"

inputs:
  report:
    description: "WCAG-EM JSON file that is the basis for your report."
    required: true
    default: "wcag-em.json"
  create-artifcat:
    description: "Upload GitHub Artifact with JSON result"
    required: false
    default: false
  create-labels:
    description: "Automatically create 78 labels in GitHub issues, one for every WCAG 2.1 succes criterion"
    required: false
    default: false
  token:
    description: "GitHub access token"
    required: true
  owner:
    description: "GitHub repository owner"
    required: true
  repo:
    description: "GitHub repository"
    required: true

outputs:
  json:
    description: "WCAG-EM JSON file"

runs:
  using: node20
  main: src/github-action.mjs
