name: "WCAG issues"
description: "Include WCAG related GitHub issues in your WCAG-EM report."
author: "Frameless"

inputs:
  input:
    description: "WCAG-EM JSON file that is the basis for your report."
    required: false
    default: "wcag-evaluation.json"
  create-artifact:
    description: "Upload GitHub Artifact with JSON result"
    required: false
    default: false
  create-labels:
    description: "Automatically create 78 labels in GitHub issues, one for every WCAG 2.1 succes criterion"
    required: false
    default: false
  label-color:
    description: "Hex-color for all WCAG labels that will be created. Use six characters, without the leading `#`."
    required: false
    default: "D93F0B"
  token:
    description: "GitHub access token"
    required: true
  owner:
    description: "GitHub repository owner"
    required: true
  repo:
    description: "GitHub repository"
    required: true
  website:
    description: "URL of the website the WCAG compliance report is about."
    required: true
  description:
    description: "Describe the scope of the evaluation."
    required: false
  title:
    description: "Title of the evaluation report."
    required: false

outputs:
  json:
    description: "WCAG-EM JSON file"

runs:
  using: node20
  main: dist/index.mjs
