name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          website: https://github.com/frameless/wcag-issues-action/
          label-color: D93F0B
          owner: frameless
          repo: wcag-issues-action
          input: wcag-em.json
          create-labels: true
          create-artifact: false
          token: ${{ secrets.GH_ISSUES_TOKEN }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.count }}"

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
